### ISSUE TITLE
J'ai un problème

### ISSUE THREAD

**Issue by Fifoudu388** [lapatatedouce59/pcc_pmd#6]
Bonjour,
J'ai un problème avec le pcc quand je le demarre j'ai une erreur vous pouvez voir ci joint
![image](https://github.com/lapatatedouce59/pcc_pmd/assets/147874120/96d0f09a-66d6-44b4-9feb-daa18e4e7421)
![image](https://github.com/lapatatedouce59/pcc_pmd/assets/147874120/b5349384-abd8-43ad-af81-7b0b005334a2)

Merci

**Comment by lapatatedouce59** [comment]
Bonjour.
Il ne s'agit pas d'une erreur mais d'un comportement attendu du programme.
Ici c'est une perte de detection positive, donc une rame a été dépreparée hors zone garage (c'est pourtant indiqué sur les formats...)
Pour toutes demandes merci de rejoindre le serveur Discord et de ne pas ouvrir une issue (les issues sont réservées aux erreurs dans le code, ici le programme réagis tout a fait normalement comme prévu).
Bonne soirée
